# See README for expected site configuration parameters

title_name: Eva
given_name: Eva
tagline: Jekyll portfolio theme

social:
  links:
    - https://www.instagram.com/anileated/

url:

email: eva@strogonoff.name

# Language in the format outlined here:
# https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang
language: en

plugins:
  - jekyll-responsive-image

responsive_image:
  template: _includes/_responsive_image.html
  sizes:
    - width: 480
      quality: 80
    - width: 800
